# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.data_transform:
        class: AppBundle\Core\Services\DataTransform
        autowire: true

    app.categoria:
        class: AppBundle\Service\CategoriaService
        autowire: true

    app.almacen:
        class: AppBundle\Service\AlmacenService
        autowire: true

    app.producto:
        class: AppBundle\Service\ProductoService
        autowire: true

    app.compra:
        class: AppBundle\Service\CompraService
        autowire: true

    app.venta:
        class: AppBundle\Service\VentaService
        autowire: true


